### PR TITLE
Auto-Format Azure.psm1 file using VSCode (No code change)

### PR DESCRIPTION
**Pull request by iamshital**

### CODE REVIEW

**Comment by iamshital** [comment]
@juhlee-microsoft Not to merge until PR #292 is merged.
If there are any code conflicts later, I'll fix them.

**Comment by ader1990** [comment]
@iamshital you can also fix the pester issues while you are at it.

**Comment by ader1990** [comment]
also, no need for 7 commits, squash them to only one commit

**Comment by iamshital** [comment]
Ju, please make it to Nov-2018.

**Comment by ader1990** [comment]
You can change the commit/Pr message to - no logic change, as you do a code change

**Comment by juhlee-microsoft** [comment]
> You can change the commit/Pr message to - no logic change, as you do a code change

@iamshital @ader1990 does it mean new code will be zero error/warning of PS Script Analyzer? Is this your effort, @iamshital ?

**Comment by iamshital** [comment]
@juhlee-microsoft @ader1990 , Fixing the PSScriptAnalyser will required changing of the function names as well. This PR only targets to fix the indents and formatting issues. Nothing else. Fixing the PSScriptAnalyser issues will take some time and proper validation.

**Comment by iamshital** [comment]
Closing this for #343

**Pull request closed without merging**
