### PR TITLE
Revert "Remove enable root for each case."

### PR DESCRIPTION
**Pull request by ader1990**
Reverts LIS/LISAv2#487
@juhlee-microsoft  please don t merge it before all agree is fine.

### CODE REVIEW

**Comment by juhlee-microsoft** [comment]
@ader1990 I see all test result posting as request. What else do you have?

**Comment by ader1990** [comment]
@juhlee-microsoft  please approve this PR and merge it, lisa is broken now.

**Comment by juhlee-microsoft** [comment]
@ader1990 Please help me understand what broke in LISAv2.

**Comment by ader1990** [comment]
hello @juhlee-microsoft . All the tests that use root user, and there are a few. @LiliDeng and @asofron can give you more exact details the exact names of which test cases. We need a full run to make sure that everything is in order before this merge.

**Pull request merged**
