### PR TITLE
Coding Style update

### PR DESCRIPTION
**Pull request by juhlee-microsoft**
Removed tailing spaces
Use tab not spaces
Coding style change per PSScript-Analyzer tool

Validated the change throught cmdline PROVISIONING test.
-----------------------
8/17/2018 06:01:01 : [INFO ] Test script: BVT-VERIFY-DEPLOYMENT-PROVISION.ps1 started.
08/17/2018 06:01:01 : [INFO ] Check 1: Checking call tracess again after 30 seconds sleep
08/17/2018 06:01:32 : [INFO ] Waiting until VMs restart...
08/17/2018 06:01:33 : [INFO ] Trying to Connect to deployed VM(s)
08/17/2018 06:01:33 : [INFO ] ALL VM's SSH port is/are open now..
08/17/2018 06:01:33 : [INFO ] Check 2: Checking call tracess again after Reboot > 30 seconds sleep
08/17/2018 06:02:03 : [INFO ] Test Result : PASS.
08/17/2018 06:02:03 : [INFO ] VM CLEANUP ~~~~~~~~~~~~~~~~~~~~~~~
08/17/2018 06:02:03 : [INFO ] Skipping cleanup, as No services / resource groups / HyperV Groups deployed for cleanup!
08/17/2018 06:02:03 : [INFO ] ~~~~~~~~~~~~~~~TEST END : VERIFY-DEPLOYMENT-PROVISION~~~~~~~~~~
08/17/2018 06:02:03 : [INFO ] CURRENT - PASS    - 1
08/17/2018 06:02:03 : [INFO ] CURRENT - FAIL    - 0
08/17/2018 06:02:03 : [INFO ] CURRENT - ABORTED - 0
08/17/2018 06:02:03 : [INFO ] Checking background cleanup jobs..
08/17/2018 06:02:03 : [INFO ] Removed 0 context files.
08/17/2018 06:02:03 : [INFO ] Cycle Finished.. TC-73622
08/17/2018 06:02:04 : [INFO ]
Test Results Summary
ICA test run on 08/17/2018 05:58:22
ARM Image under test Canonical : UbuntuServer : 18.04-LTS : latest
Total Executed TestCases        1 (       1 Pass,        0 Fail,        0 Abort)
Total Execution Time(dd:hh:mm) 0:0:3
XML file: TestConfiguration

VERIFY-DEPLOYMENT-PROVISION Execution Time: 3.56 minutes
        VERIFY-DEPLOYMENT-PROVISION : PASS
                  FirstBoot : PASS
                  FirstBoot : Call Trace Verification : PASS
                  Reboot : PASS
                  Reboot : Call Trace Verification : PASS

Logs can be found at .\TestResults\2018-16-08-22-58-08-7575

08/17/2018 06:02:04 : [INFO ] Creating 'Azure-73622-buildlogs.zip' from '.\TestResults\2018-16-08-22-58-08-7575'
08/17/2018 06:02:04 : [INFO ] C:\LISAv2\REKO73622\Azure-73622-buildlogs.zip created successfully.
08/17/2018 06:02:04 : [INFO ] Copied : .\report\report_TC-73622.xml --> .\report\report_TC-73622-junit.xml
08/17/2018 06:02:04 : [INFO ] Analysing results..
08/17/2018 06:02:04 : [INFO ] PASS  : 1
08/17/2018 06:02:04 : [INFO ] FAIL  : 0
08/17/2018 06:02:04 : [INFO ] ABORT : 0
Copying all files back to original working directory: C:\Users\juhlee\Source\Repos\LISAv2.
Cleaning up C:\LISAv2\REKO73622
Setting workspace back to original location: C:\Users\juhlee\Source\Repos\LISAv2
08/17/2018 06:02:37 : [INFO ] LISAv2 exits with code: 0

### CODE REVIEW

**Comment by ader1990** [comment]
@iamshital those uneven indents on json should be removed. also, using a json parser native to the powershell should be used (but in another PR)

**Comment by ader1990** [comment]
@juhlee-microsoft what rules for invoke-scryptanalyzer did you fix? can you share the cmd you ran for scrypt analizer and how many issues did you fix?

**Comment by juhlee-microsoft** [comment]
@ader1990 I used below command line in Libraries folder. 
C:\>Invoke-ScriptAnalyzer .\Azure.psm1
1. defined but never used variables: 30
2. trailing white spaces: 157
3. PS Cmdlet Alias use: 20
4. incorrect comparison with numm: 7
5. avoid empty catch block: 1

**Comment by ader1990** [comment]
great, this improves the code quality alot.

**Comment by juhlee-microsoft** [comment]
I hope this tool should be a part of PR preparation. We have coding recommendation in how-to-use page also. I also saw 1) mixing space with tab, 2) indentation issue, 3) old comments/debug snippets.

**Comment by juhlee-microsoft** [comment]
@iamshital do you still want to hold this PR?

**Comment by iamshital** [comment]
@ader1990 Indents in JSON are not uneven. If you look the created JSON file, it follows proper indentation.

**Comment by iamshital** [comment]
@juhlee-microsoft  Please test Storage Performance and Network Performance tests against Ubuntu 1604. Will signoff once done.

**Comment by juhlee-microsoft** [comment]
**Test log** 

-----------------------------------------------------------------
08/17/2018 22:50:40 : [INFO ] ~~~~~~~~~~~~~~~TEST END : PERF-NETWORK-TCP-SINGLE-CONNECTION-THROUGHPUT-Synthetic~~~~~~~~~~
08/17/2018 22:50:40 : [INFO ] CURRENT - PASS    - 0
08/17/2018 22:50:40 : [INFO ] CURRENT - FAIL    - 0
08/17/2018 22:50:40 : [INFO ] CURRENT - ABORTED - 1
08/17/2018 22:50:40 : [INFO ] Job101 is running.
08/17/2018 22:50:40 : [INFO ] Checking background cleanup jobs..
08/17/2018 22:50:40 : [INFO ] Removed 0 context files.
08/17/2018 22:50:40 : [INFO ] Cycle Finished.. TC-72241
08/17/2018 22:50:41 : [INFO ]
Test Results Summary
ICA test run on 08/17/2018 22:42:23
ARM Image under test Canonical : UbuntuServer : 18.04-LTS : latest
Total Executed TestCases         1 (        0 Pass,         0 Fail,         1 Abort)
Total Execution Time(dd:hh:mm) 0:0:8
XML file: TestConfiguration

PERF-NETWORK-TCP-SINGLE-CONNECTION-THROUGHPUT-Synthetic Execution Time: 8.23 minutes
        PERF-NETWORK-TCP-SINGLE-CONNECTION-THROUGHPUT-Synthetic : ABORTED


Logs can be found at .\TestResults\2018-17-08-15-42-14-4474


08/17/2018 22:50:41 : [INFO ] Creating 'Azure-72241-buildlogs.zip' from '.\TestResults\2018-17-08-15-42-14-4474'
08/17/2018 22:50:41 : [INFO ] C:\LISAv2\BLCR72241\Azure-72241-buildlogs.zip created successfully.
08/17/2018 22:50:41 : [INFO ] Copied : .\report\report_TC-72241.xml --> .\report\report_TC-72241-junit.xml
08/17/2018 22:50:41 : [INFO ] Analysing results..
08/17/2018 22:50:41 : [INFO ] PASS  : 0
08/17/2018 22:50:41 : [INFO ] FAIL  : 0
08/17/2018 22:50:41 : [INFO ] ABORT : 1
Copying all files back to original working directory: C:\Users\juhlee\Source\Repos\LISAv2-exec.
Cleaning up C:\LISAv2\BLCR72241
Setting workspace back to original location: C:\Users\juhlee\Source\Repos\LISAv2-exec
08/17/2018 22:50:51 : [INFO ] LISAv2 exits with code: 1
PS C:\Users\juhlee\Source\Repos\LISAv2-exec>

**Comment by juhlee-microsoft** [comment]
Ran many network perf tests in congested regions and finally found one test pass from good region. Will do storage perf test when I am back from vacation.

**Comment by juhlee-microsoft** [comment]
Perf-tests with synthetic and SR-IOV kept failing with various options. I don't think I can review thousands of changed lines for the fix. Re-do in another PR next time.

**Pull request closed without merging**
