### PR TITLE
No need enable root for testing on Azure.

### PR DESCRIPTION
**Pull request by LiliDeng**
Run case against Azure and HyperV pass (TestCategory BVT)

### CODE REVIEW

**Comment by chvalean** [comment]
Common tests for Azure and Hyper-V or even standalone ones for Hyper-V only would have the same behavior - either require root or not.
So I don't think the difference to enable root user for Hyper-V only is something applicable per platform.
Or do you have any specific examples?

**Comment by LiliDeng** [comment]
Please hold on this PR, I want to run perf testing to make sure not break them.

**Comment by juhlee-microsoft** [comment]
I found your msg later, if you see any perf issue, please open a bug.

**Comment by chvalean** [comment]
@juhlee-microsoft  this should not have been merged based on my question to Lili.
I don't understand why there is a Hyper-V inclusion only to run Enable-RootUser.
Independent on the platform - Azure or Hyper-V, triggering Enable-RootUser should not be required on one or the other.

**Comment by juhlee-microsoft** [comment]
Oops. I missed it. Will look into this afternoon and find way to fix.


________________________________

**Pull request merged**
