### PR TITLE
Remove enable root for each case.

### PR DESCRIPTION
**Pull request by LiliDeng**

### CODE REVIEW

**Comment by adriansuhov** [comment]
This PR has to be thoroughly tested with all the azure and hyper-v test cases to see which tests are affected.

**Comment by ader1990** [comment]
Please make sure there is at least one test case run which has two vms, preferably a HyperV perf test case.

**Comment by LiliDeng** [comment]
Total  I ran 54 cases against Hyper-V.
As I see from log, SQM-BASIC, KVP-PUSH-KEY-VALUES, MAX-VCPU and PAUSED-CRITICAL-HEARTBEAT  abort for hardcode root. For other abort/fail cases, I don't have time to rerun and double check, I will make sure this change won't break testing on azure platform

=======Category - Functional Area - KVP======= 11

   ID TestCaseName                                                 TestResult TestDuration(in minutes) 
------------------------------------------------------------------------------------------------------
    1 SQM-BASIC                                                       ABORTED                 5.53 
    2 KVP-INTRINSIC                                                      PASS                 1.31 
    3 KVP-BASIC-CHECKS                                                   PASS                 3.74 
    4 KVP-ADD-KEY-VALUES                                                 PASS                 2.91 
    5 KVP-MODIFY-KEY-VALUES                                              PASS                  2.2 
    6 KVP-REMOVE-KEY-VALUES                                              PASS                 0.91 
    7 KVP-PUSH-KEY-VALUES                                             ABORTED                 3.51 
    8 KVP-DELETE-NON-EXIST-KVP-ON-GUEST                                  PASS                 1.44 
    9 KVP-MODIFY-NON-EXIST-KVP-ON-GUEST                                  PASS                 1.32 
   10 KVP-TEST-RESCIND                                                   FAIL                 5.44 
   11 KVP-MAX-READ                                                    Aborted                 2.16 


=======Category - BVT ======= 16
   ID TestCaseName                                                 TestResult TestDuration(in minutes) 
------------------------------------------------------------------------------------------------------
    1 BVT-VERIFY-DEPLOYMENT-PROVISION                                    PASS                 5.93 
	FirstBoot : PASS 
	FirstBoot : Call Trace Verification : PASS 
	Reboot : PASS 
	Reboot : Call Trace Verification : PASS 
    2 BVT-CORE-TIMESYNC-NTP                                              PASS                 2.79 
    3 BVT-CORE-VERIFY-LIS-MODULES                                        PASS                 2.05 
    4 BVT-CORE-VERIFY-LIS-MODULES-VERSION                                PASS                 2.22 
    5 BVT-CORE-RELOAD-MODULES-SMP                                        PASS                14.79 
    6 BVT-CORE-TIME-CLOCKSOURCE                                          PASS                 4.48 
    7 BVT-CORE-TIME-CLOCKEVENT-UP                                        PASS                 9.27 
    8 BVT-CORE-TIME-CLOCKEVENT-SMP                                    ABORTED                 4.33 
    9 BVT-NET-ETHTOOL-CHECK-KEYS                                      ABORTED                 4.98 
   10 BVT-NET-ETHTOOL-CHANGE-RINGBUFFER                                  PASS                 5.96 
   11 BVT-NET-ETHTOOL-TCP-HASHLEVELS                                     PASS                 2.36 
   12 BVT-NET-ETHTOOL-UDP-HASHLEVELS                                     PASS                 2.37 
   13 BVT-NET-ETHTOOL-GRO-LRO                                            PASS                 2.41 
   14 BVT-NET-ETHTOOL-CHECK-CHANNEL                                      PASS                 2.16 
   15 BVT-NET-IFUP-IFDOWN                                             ABORTED                 4.17  need debug
   16 VERIFY-DEPLOYMENT-PROVISION                                        PASS                 3.95 
	FirstBoot : PASS 
	FirstBoot : Call Trace Verification : PASS 
	Reboot : PASS 
	Reboot : Call Trace Verification : PASS 
	
=======Category - Functional Area - LIS======= 10
[LISAv2 Test Results Summary]
   ID TestCaseName                                                 TestResult TestDuration(in minutes) 
------------------------------------------------------------------------------------------------------
    1 LIS-CHECK-HYPERVDAEMONS-FILES-STATUS                               FAIL                 7.34 
    2 LIS-MOUNT-FLOPPYDISK                                               PASS                 2.47 
    3 LIS-MOUNT-CD                                                       PASS                 4.53 
    4 LIS-MOUNT-CD-HOTADD                                                PASS                 4.08 
    5 VMBUS_VERIFY_PROTOCOL_VERSION                                      PASS                 2.47 
    6 VMBUS_VERIFY_INTERRUPTS                                            PASS                 6.43 
    7 VMBUS_PANIC_NOTIFIER                                               FAIL                22.47 
    8 VMBUS_PANIC_NOTIFIER_KDUMP                                         FAIL                21.35 
    9 NMI_VERIFY_INTERRUPT                                               PASS                 2.46 
   10 NMI_VERIFY_FAILED_INTERRUPT                                        PASS                 3.76  
	
=======Category - Functional Area -Core======= 17
   ID TestCaseName                                                 TestResult TestDuration(in minutes) 
------------------------------------------------------------------------------------------------------
    1 VERIFY-HEARTBEAT                                                   PASS                 3.56 
    2 VERIFY-VM-SHUTDOWN                                                 PASS                 2.72 
    3 VERIFY-TIME-SYNC                                                   PASS                 3.75 
    4 INITRD-MODULES-CHECK                                               PASS                 3.36 
    5 CPU-VERIFY-ONLINE                                                  PASS                 2.13 
    6 LSVMBUS                                                            PASS                 2.67 
    7 MAX-VCPU                                                        ABORTED                 6.32 
    8 PAUSED-CRITICAL-HEARTBEAT                                       ABORTED                 5.31 
    9 CHECK-NUMA                                                         PASS                 2.93 
   10 CHECK-NUMA-MAXIMUM                                                 PASS                 3.02 
   11 REBOOT-DIFFERENT-MEMORY-SETTINGS                                   PASS                  5.1 
   12 TIMESYNC-BASIC                                                     PASS                 2.85 
   13 TIMESYNC-SAVEDVM                                                   PASS                13.09 
   14 TIMESYNC-PAUSEDVM                                                  PASS                12.83 
   15 TIMESYNC-SAVEDVM-CHRONYOFF                                         PASS                 9.64 
   16 TIMESYNC-PAUSEDVM-CHRONYOFF                                        PASS                  9.1 
   17 TIMESYNC-VDSO                                                   Aborted                 2.28

**Comment by lizzha** [comment]
@LiliDeng, could you still go with the previous change to make it conditional for HyperV/Azure currently, the fix for HyperV should be in later PRs

**Comment by LiliDeng** [comment]
I see

**Comment by LiliDeng** [comment]
I will push the update for azure platform once done the regression.
Category - BVT results
BVT-VERIFY-BOOT-ERROR-WARNINGS failure not caused by my changes.

Test Run On           : 12/05/2018 03:06:56
ARM Image Under Test  : canonical : ubuntuserver : 18.04-lts : Latest
Total Test Cases      : 36 (35 Pass, 1 Fail, 0 Abort)
Total Time (dd:hh:mm) : 0:2:30
XML File              : TestConfiguration

   ID TestCaseName                                                 TestResult TestDuration(in minutes) 
------------------------------------------------------------------------------------------------------
    1 BVT-VERIFY-DEPLOYMENT-PROVISION                                    PASS                 8.37 
	FirstBoot : PASS 
	FirstBoot : Call Trace Verification : PASS 
	Reboot : PASS 
	Reboot : Call Trace Verification : PASS 
    2 BVT-IS-ROOT-PASSWORD-DELETED                                       PASS                  2.4 
    3 BVT-ROOT-DEVICE-TIMEOUT-CHECK                                      PASS                 2.39 
    4 BVT-HVMODULES-CHECK                                                PASS                 2.39 
    5 BVT-SWAP-CHECK                                                     PASS                 2.39 
    6 BVT-MTAB-ENTRY-CHECK                                               PASS                 2.47 
    7 BVT-LAST-CONSOLE-CHECK                                             PASS                 2.38 
    8 BVT-VERIFY-BOOT-ERROR-WARNINGS                                     FAIL                 3.18 
    9 BVT-VERIFY-SHUTDOWN                                                PASS                 5.22 
   10 BVT-VERIFY-RESTART                                                 PASS                  2.6 
   11 BVT-VERIFY-UUID-FSTAB                                              PASS                  2.4 
   12 BVT-VERIFY-SSHD-CONFIG                                             PASS                 2.79 
   13 BVT-VERIFY-VHD-PREREQUISITES                                       PASS                 2.77 
   14 BVT-VERIFY-NO-ERROR-IN-LOGS                                        PASS                 2.47 
   15 BVT-VERIFY-VERBOSE-ENABLED-LOGS                                    PASS                 3.95 
   16 BVT-VERIFY-BASH-HISTORY                                            PASS                 2.58 
   17 BVT-PASSWD-POLICY-TEST                                             PASS                 2.57 
   18 BVT-VERIFY-KVP-DAEMON-STATUS                                       PASS                  3.6 
   19 BVT-CORE-TIMESYNC-NTP                                              PASS                 4.04 
   20 BVT-CORE-VERIFY-LIS-MODULES                                        PASS                 2.57 
   21 BVT-CORE-VERIFY-LIS-MODULES-VERSION                                PASS                 2.41 
   22 BVT-CORE-RELOAD-MODULES-SMP                                        PASS                16.88 
   23 BVT-CORE-TIME-CLOCKSOURCE                                          PASS                 5.54 
   24 BVT-CORE-TIME-CLOCKEVENT-UP                                        PASS                 2.19 
   25 BVT-CORE-TIME-CLOCKEVENT-SMP                                       PASS                 5.77 
   26 BVT-NET-ETHTOOL-CHECK-KEYS                                         PASS                 5.68 
   27 BVT-NET-ETHTOOL-CHANGE-RINGBUFFER                                  PASS                 2.32 
   28 BVT-NET-ETHTOOL-TCP-HASHLEVELS                                     PASS                 2.31 
   29 BVT-NET-ETHTOOL-UDP-HASHLEVELS                                     PASS                 2.32 
   30 BVT-NET-ETHTOOL-GRO-LRO                                            PASS                 2.32 
   31 BVT-NET-ETHTOOL-CHECK-CHANNEL                                      PASS                 2.31 
   32 BVT-NET-IFUP-IFDOWN                                                PASS                 5.58 
   33 VERIFY-DEPLOYMENT-PROVISION                                        PASS                 4.09 
	FirstBoot : PASS 
	FirstBoot : Call Trace Verification : PASS 
	Reboot : PASS 
	Reboot : Call Trace Verification : PASS 
   34 VERIFY-DEPLOYMENT-PROVISION-EPHEMERAL-MANAGED-DISK                 PASS                 8.44 
	FirstBoot : PASS 
	FirstBoot : Call Trace Verification : PASS 
	Reboot : PASS 
	Reboot : Call Trace Verification : PASS 
   35 VERIFY-DEPLOYMENT-PROVISION-SRIOV                                  PASS                 7.43 
	FirstBoot : PASS 
	FirstBoot : Call Trace Verification : PASS 
	Reboot : PASS 
	Reboot : Call Trace Verification : PASS 
   36 VERIFY-HOSTNAME                                                    PASS                 5.69

**Comment by LiliDeng** [comment]
Many functional testing is broken in azure platform, fixing

**Comment by chvalean** [comment]
@LiliDeng Andrei is also working on fixing the scripts, please sync on the list of tests to not overlap.

**Pull request merged**
