### PR TITLE
code_style: added more rules to flake8 and shellcheck

### PR DESCRIPTION
**Pull request by ader1990**

### CODE REVIEW

**Comment by ader1990** [comment]
This patch is adding more code style rules for Python and enabling shellchecker rules for Bash code.

@juhlee-microsoft @simonxiaoss @lizzha let me know if I should add/remove rules.

**Comment by ader1990** [comment]
@juhlee-microsoft that s why I asked you to confirm how many rules to be added. let me know and I will remove/add the ones that you prefer.

**Comment by lizzha** [comment]
Ava and Tong can help on this. Since there're many errors, we need to split the fix into several PRs.

**Comment by juhlee-microsoft** [comment]
> @juhlee-microsoft that s why I asked you to confirm how many rules to be added. let me know and I will remove/add the ones that you prefer.
> 
> That long line of rules are the excluded ones, as there is no way for the moment to include only the desired ones, we can only exclude them. pls check issue opened here: [koalaman/shellcheck#1394](https://github.com/koalaman/shellcheck/issues/1394)

@ader1990 it is better for you to explain each rule in the PR and help others understanding why you proposed them. @lizzha team can handle each rule. Is it possible to post each rule's result in this PR instead of several PRs?

**Comment by chvalean** [comment]
> > @juhlee-microsoft that s why I asked you to confirm how many rules to be added. let me know and I will remove/add the ones that you prefer.
> > That long line of rules are the excluded ones, as there is no way for the moment to include only the desired ones, we can only exclude them. pls check issue opened here: [koalaman/shellcheck#1394](https://github.com/koalaman/shellcheck/issues/1394)
> 
> @ader1990 it is better for you to explain each rule in the PR and help others understanding why you proposed them. @lizzha team can handle each rule. Is it possible to post each rule's result in this PR instead of several PRs?

The explanations would be too long for this.
Those can be checked here for example, replace SC ID with the desired one.
https://github.com/koalaman/shellcheck/wiki/SC1000

**Comment by LiliDeng** [comment]
Fix for flake8 done - see  [PR 473](https://github.com/LIS/LISAv2/pull/473)

**Comment by juhlee-microsoft** [comment]
@ader1990 please resolve the conflict. I can merge this.

**Comment by LiliDeng** [comment]
@juhlee-microsoft Don't merge this. We split this into two PR.
One is for python - #473 , it is merged.
The other is for shell check - code is ready, we are testing it locally, hopefully we can submit PR within this week. 
Let know if you are clear now.

**Comment by juhlee-microsoft** [comment]
@ader1990 @LiliDeng how soon can you close this?

**Comment by LiliDeng** [comment]
@juhlee-microsoft Today, we will create a PR for parts of them, since we can't run all scripts, like cluster cases etc.

**Comment by juhlee-microsoft** [comment]
> @juhlee-microsoft Today, we will create a PR for parts of them, since we can't run all scripts, like cluster cases etc.

@LiliDeng @ader1990 any update of the completion ETA?

**Comment by ader1990** [comment]
@juhlee-microsoft this PR will be updated after the refactor is merged

**Comment by chvalean** [comment]
Part of the changes for shell are done in PR https://github.com/LIS/LISAv2/pull/546

**Comment by LiliDeng** [comment]
Still working on remain parts, ETA is end of this month. Thanks!

**Comment by ader1990** [comment]
closing this PR, as https://github.com/LIS/LISAv2/pull/629 will implement the shellcheck changes.
@v-sijliu please add the required stage to check for shellcheck rules.

**Pull request closed without merging**
