### PR TITLE
 Updated script to upload multi-core dpdk results into database

### PR DESCRIPTION
**Pull request by rmsivakanth**

### CODE REVIEW

**Comment by rmsivakanth** [comment]
Execution is verified.
```
Ubuntu 18.04:
09/11/2018 03:22:59 : [INFO ] ~~~~~~~~~~~~~~~TEST END : PERF-DPDK-MULTICORE-PPS-DS15~~~~~~~~~~
09/11/2018 03:22:59 : [INFO ] CURRENT - PASS    - 1
09/11/2018 03:22:59 : [INFO ] CURRENT - FAIL    - 0
09/11/2018 03:22:59 : [INFO ] CURRENT - ABORTED - 0
09/11/2018 03:22:59 : [INFO ] Checking background cleanup jobs..
09/11/2018 03:22:59 : [INFO ] Removed 0 context files.
09/11/2018 03:22:59 : [INFO ] Cycle Finished.. TC-22909
09/11/2018 03:22:59 : [INFO ]
Test Results Summary
ICA test run on 09/11/2018 02:51:39
ARM Image under test Canonical : UbuntuServer : 18.04-LTS : latest
Total Executed TestCases        1 (       1 Pass,        0 Fail,        0 Abort)
Total Execution Time(dd:hh:mm) 0:0:31
XML file: TestConfiguration

PERF-DPDK-MULTICORE-PPS-DS15 Execution Time: 31.25 minutes
        PERF-DPDK-MULTICORE-PPS-DS15 : PASS
                  DPDK-TESTPMD : PASS

Logs can be found at .\TestResults\2018-10-09-19-51-20-6504

09/11/2018 03:22:59 : [INFO ] Creating 'Azure-22909-buildlogs.zip' from '.\TestResults\2018-10-09-19-51-20-6504'
09/11/2018 03:23:00 : [INFO ] C:\Users\v-sirebb\Documents\GitHub\LISAv2\Azure-22909-buildlogs.zip created successfully.
09/11/2018 03:23:00 : [INFO ] Copied : .\report\report_TC-22909.xml --> .\report\report_TC-22909-junit.xml
09/11/2018 03:23:00 : [INFO ] Analysing results..
09/11/2018 03:23:00 : [INFO ] PASS  : 1
09/11/2018 03:23:00 : [INFO ] FAIL  : 0
09/11/2018 03:23:00 : [INFO ] ABORT : 0
09/11/2018 03:23:00 : [INFO ] LISAv2 exits with code: 0

RHEL 7.5:
09/11/2018 04:45:23 : [INFO ] ~~~~~~~~~~~~~~~TEST END : PERF-DPDK-SINGLE-CORE-PPS-DS15~~~~~~~~~~
09/11/2018 04:45:23 : [INFO ] CURRENT - PASS    - 1
09/11/2018 04:45:23 : [INFO ] CURRENT - FAIL    - 0
09/11/2018 04:45:23 : [INFO ] CURRENT - ABORTED - 0
09/11/2018 04:45:23 : [INFO ] Checking background cleanup jobs..
09/11/2018 04:45:23 : [INFO ] Removed 0 context files.
09/11/2018 04:45:23 : [INFO ] Cycle Finished.. TC-99499
09/11/2018 04:45:23 : [INFO ]
Test Results Summary
ICA test run on 09/11/2018 04:25:59
ARM Image under test RedHat : RHEL : 7-RAW : 7.5.2018042521
Total Executed TestCases        1 (       1 Pass,        0 Fail,        0 Abort)
Total Execution Time(dd:hh:mm) 0:0:19
XML file: TestConfiguration

PERF-DPDK-SINGLE-CORE-PPS-DS15 Execution Time: 19.29 minutes
        PERF-DPDK-SINGLE-CORE-PPS-DS15 : PASS
                  DPDK-TESTPMD : PASS


Logs can be found at .\TestResults\2018-10-09-21-25-27-9258


09/11/2018 04:45:23 : [INFO ] Creating 'Azure-99499-buildlogs.zip' from '.\TestResults\2018-10-09-21-25-27-9258'
09/11/2018 04:45:24 : [INFO ] C:\Users\v-sirebb\Documents\GitHub\LISAv2\Azure-99499-buildlogs.zip created successfully.
09/11/2018 04:45:24 : [INFO ] Copied : .\report\report_TC-99499.xml --> .\report\report_TC-99499-junit.xml
09/11/2018 04:45:24 : [INFO ] Analysing results..
09/11/2018 04:45:24 : [INFO ] PASS  : 1
09/11/2018 04:45:24 : [INFO ] FAIL  : 0
09/11/2018 04:45:24 : [INFO ] ABORT : 0
09/11/2018 04:45:24 : [INFO ] LISAv2 exits with code: 0
```

**Comment by rmsivakanth** [comment]
I have ran PS Script Analyzer tool and there is no unused variables now.

**Comment by juhlee-microsoft** [comment]
>           I have ran PS Script Analyzer tool and there is no unused variables now.

I see your fix. Can you re-run other tests before merging?

**Comment by rmsivakanth** [comment]
Execution is verified.
```
09/12/2018 21:26:31 : [INFO ] ~~~~~~~~~~~~~~~TEST END : PERF-DPDK-MULTICORE-PPS-DS15~~~~~~~~~~
09/12/2018 21:26:31 : [INFO ] CURRENT - PASS    - 4
09/12/2018 21:26:31 : [INFO ] CURRENT - FAIL    - 0
09/12/2018 21:26:31 : [INFO ] CURRENT - ABORTED - 0
09/12/2018 21:26:31 : [INFO ] Checking background cleanup jobs..
09/12/2018 21:26:31 : [INFO ] Removed 0 context files.
09/12/2018 21:26:31 : [INFO ] Cycle Finished.. TC-51895
09/12/2018 21:26:31 : [INFO ] 
Test Results Summary
ICA test run on 09/12/2018 20:02:40
ARM Image under test Canonical : UbuntuServer : 18.04-LTS : latest
Total Executed TestCases        4 (       4 Pass,        0 Fail,        0 Abort)
Total Execution Time(dd:hh:mm) 0:1:23
XML file: TestConfiguration

VERIFY-DPDK-BUILD-AND-TESTPMD-TEST Execution Time: 23.33 minutes
	VERIFY-DPDK-BUILD-AND-TESTPMD-TEST : PASS  
PERF-DPDK-SINGLE-CORE-PPS-DS4 Execution Time: 15.56 minutes
	PERF-DPDK-SINGLE-CORE-PPS-DS4 : PASS  
		  DPDK-TESTPMD : PASS 
PERF-DPDK-SINGLE-CORE-PPS-DS15 Execution Time: 14.93 minutes
	PERF-DPDK-SINGLE-CORE-PPS-DS15 : PASS  
		  DPDK-TESTPMD : PASS 
PERF-DPDK-MULTICORE-PPS-DS15 Execution Time: 29.99 minutes
	PERF-DPDK-MULTICORE-PPS-DS15 : PASS  
		  DPDK-TESTPMD : PASS 


Logs can be found at .\TestResults\2018-12-09-20-02-33-7514


09/12/2018 21:26:31 : [INFO ] Creating 'Azure-51895-buildlogs.zip' from '.\TestResults\2018-12-09-20-02-33-7514'
09/12/2018 21:26:32 : [INFO ] C:\LISAv2\LKUW51895\Azure-51895-buildlogs.zip created successfully.
09/12/2018 21:26:32 : [INFO ] Copied : .\report\report_TC-51895.xml --> .\report\report_TC-51895-junit.xml
09/12/2018 21:26:32 : [INFO ] Analysing results..
09/12/2018 21:26:32 : [INFO ] PASS  : 4
09/12/2018 21:26:32 : [INFO ] FAIL  : 0
09/12/2018 21:26:32 : [INFO ] ABORT : 0
Copying all files back to original working directory: C:\Jenkins-Slaves\azure-slave-2-executor-8\workspace\job-azuretest\pipeline-dpdk.
Cleaning up C:\LISAv2\LKUW51895
Setting workspace back to original location: C:\Jenkins-Slaves\azure-slave-2-executor-8\workspace\job-azuretest\pipeline-dpdk
09/12/2018 21:26:34 : [INFO ] LISAv2 exits with code: 0
```

**Pull request merged**
