### PR TITLE
Added script to remove old Azure VMs

### PR DESCRIPTION
**Pull request by iamshital**

### CODE REVIEW

**Comment by iamshital** [comment]
Cleanup job successfully verified!
------------------------------------
tool-azure-cleanup-resources/6211/console

**Comment by chvalean** [comment]
@iamshital please review the PSScriptAnalyzer failures and fix.

**Comment by juhlee-microsoft** [comment]
@LiliDeng @iamshital Help me understand why we have duplicated function in LISAv2? The existing Cleanup service is removing old VM and RG.

**Comment by LiliDeng** [comment]
@juhlee-microsoft This is for Jenkins pipeline tool-azure-cleanup-resources, move from pipeline to lisav2, I double check that pipeline is using shital's branch to do clean up work currently.

**Comment by juhlee-microsoft** [comment]
@iamshital please post the test result after you fixed the PR checker issue.

**Comment by iamshital** [comment]
@prashantmhetar , Can you please send me the logs of "https://microsoft.visualstudio.com/8d47e068-03c8-4cdc-aa9b-fc6929290322/_build/results?buildId=14211972" (PR checker build).

**Comment by chvalean** [comment]
> @prashantmhetar , Can you please send me the logs of "https://microsoft.visualstudio.com/8d47e068-03c8-4cdc-aa9b-fc6929290322/_build/results?buildId=14211972" (PR checker build).

Details below:
2019-02-04T11:03:34.8321280Z RuleName                            Severity     ScriptName Line  Message                                              
2019-02-04T11:03:34.8325211Z --------                            --------     ---------- ----  -------                                              
2019-02-04T11:03:34.8343712Z PSAvoidTrailingWhitespace           Information  Remove-Old 130   Line has trailing whitespace                         
2019-02-04T11:03:34.8344299Z                                                  AzureVMs.ps1                                                                    
2019-02-04T11:03:34.8405069Z PSUseDeclaredVarsMoreThanAssignment Warning      Remove-Old 30    The variable 'xmlSecrets' is assigned but never used.
2019-02-04T11:03:34.8405355Z s                                                AzureVMs.ps1

**Comment by juhlee-microsoft** [comment]
> @juhlee-microsoft This is for Jenkins pipeline tool-azure-cleanup-resources, move from pipeline to lisav2, I double check that pipeline is using shital's branch to do clean up work currently.

Now, I understand what this PR is. @LiliDeng This PR removed his personal account use in Jenkins pipeline configuration page. Is that so? As soon as it merges to the master, please make sure of configuration page update.

**Comment by iamshital** [comment]
@juhlee-microsoft Fixed PSScriptAnalyzer errors.

**Comment by iamshital** [comment]
> > @juhlee-microsoft This is for Jenkins pipeline tool-azure-cleanup-resources, move from pipeline to lisav2, I double check that pipeline is using shital's branch to do clean up work currently.
> 
> Now, I understand what this PR is. @LiliDeng This PR removed his personal account use in Jenkins pipeline configuration page. Is that so? As soon as it merges to the master, please make sure of configuration page update.

@juhlee-microsoft  No Ju. Cleanup job never used my personal repository. The pipeline code / script was embedded in cleanup job.

**Pull request merged**
